### ISSUE TITLE
Create interfaces between reconstruction methods and libertem

### ISSUE THREAD

**Issue by heidemeissner** [Ptychography-4-0/ptychography#10]
For EPIE (DESY-version and Alpaka-version) an interface between C++ and python is required. 

Start with Achim's EPIE which is written in python to have an easy full workflow.

**Comment by uellue** [comment]
Minimal example:

* Stand-alone Python script
* Minimal Alpaka routine ("hello world" style, for example a sum to check correctness)
* Interfacing between Python and Alpaka, for example via cython, ctypes etc
* Two Python functions:
  * `init()` to set up data structures
  * Repeated calls to `process()` that moves data into the structures, triggers the Alpaka processing and receives the result

**Comment by sk1p** [comment]
See also: https://cppyy.readthedocs.io/en/latest/ for a cling-based approach to create a Python<>C++ binding

**Comment by SimeonEhrig** [comment]
A first version of a python interface is merged in the desy ePIE code and an improved version is WIP.
