### ISSUE TITLE
Poster for Helmholtz Imaging Platform matchmaking workshop

### ISSUE THREAD

**Issue by uellue** [Ptychography-4-0/ptychography#24]
**Ptychography 4.0 – An Information and Data Science Pilot Project Data infrastructure and applications**

--> Poster: [PtychoHIP_FZJ_HZB_HZDR-DiWe-0.2-web.pdf](https://github.com/Ptychography-4-0/ptychography/files/4311952/PtychoHIP_FZJ_HZB_HZDR-DiWe-0.2-web.pdf) <--

# Interest in projects

* Applications of ptychography
* Implementations of ptychography
* Solving large-scale optimization problems
* Distributed high-performance data processing
* Advanced imaging
* Data management, data logistics

# See related

* Poster P26: Imaging at Institute of Radiation Physics @HZDR: https://owncloud.hzdr.de/index.php/s/19nvqlWrUkan4zb (password: imagingFWK)
* Poster P27: Alpaka, https://owncloud.hzdr.de/index.php/s/69Zip2M4zJYhoX3 (poster, password: alpakaPoster) and https://github.com/ComputationalRadiationPhysics/alpaka
* Poster P09: LiberTEM, https://github.com/LiberTEM/LiberTEM/issues/671

# Contact

We are looking forward to collaborate on new project ideas! Contact us to arrange a follow-up discussion for details.

Alexander Clausen <a.clausen@fz-juelich.de> (FZ Jülich, LiberTEM, data logistics)
Simeon Ehrig <s.ehrig@hzdr.de> (HZDR, Alpaka, implementation)
Heide Meißner <h.meissner@hzdr.de> (HZDR, Alpaka, application)
Knut Müller-Caspary <k.mueller-caspary@fz-juelich.de> (FZ Jülich, electron microscopy)
Dieter Weber <d.weber@fz-juelich.de> (FZ Jülich, LiberTEM, application, **presenting author**)
Markus Wollgarten <wollgarten@helmholtz-berlin.de> (HZB, electron microscopy)

**Comment by heidemeissner** [comment]
Could we move the content (links and poster) somewhere to the master branch? And then close this issue?

**Comment by uellue** [comment]
Closing here!
