### ISSUE TITLE
Release version 0.1 with SSB and stitching

### ISSUE THREAD

**Issue by uellue** [Ptychography-4-0/ptychography#32]
Since the code for SSB and for stitching is pretty mature and we are about to publish a paper regarding live ptychography based on this SSB implementation, it is now time for the first release.

- [x] Handle #31 
- [x] we should merge over the CI configuration of the LiberTEM repo
- [x] including the release scripts etc.
- [x] the azure pipeline definition needs to be cleaned up a bit:
  - [x] distributed docker tests are not needed (yet?)
  - [x] no nodejs tests either
- [x] then we can configure a Azure project for Ptychography 4.0 on dev.azure.com
- [x] we also need to enable the codecov.io thingy for this repo
- [x] Edit by @uellue: Create Zenodo sandbox and production initial deposition
- [x] Edit by @uellue: Set up github.io page
- [x] Edit by @uellue: Create PyPI sandbox and production initial project?
- [x] We then need to make some secrets available to the pipeline:
  - Note @uellue: I have changed the variable names from LT_* to PTY_* in azure-pipelines.yml
  - [x] for example, the `deploy_docs` job needs to have access to a github deploy key
  - [x] and we need to generate access tokens for test.pypi.org (`libertem_bot` user?)
  - [x] and for pypi.org
  - [x] and for sandbox.zenodo.org
  - [x] and for zenodo.org
- [x] we can then also add links on https://github.com/liberTEM/libertem.github.io (it's very simple, just change the readme.md)
- [N/A] for tests w/ data access, need to add a second azure pipeline, possibly with its own runner (not sure the other runner can/should be made available to different projects) → moved to #51

## Dependencies

- [x] Release LiberTEM and LiberTEM-live with prerequisites for #35
- [x] Merge #35 

## Before (using a release candidate package)

- [x] Clean up `references*.bib`
- [x] Review open issues and pull requests
- [x] Handle deprecation, search the code base for `DeprecationWarning` that are supposed to be removed in that release.
- [x] Full documentation review and update, including link check using `sphinx-build -b linkcheck "docs/source" "docs/build/html"`
- [x] Review and approval by co-authors for first release
- [ ] Run complete test suite, including slow tests that are deactivated by default and tests that require sample files. Also run tests that require a GPU.
- [x] Update the expected version in notes on changes, i.e. from `0.3.0.dev0` to `0.3.0` when releasing version 0.3.0.
- [x] Update and review change log in `docs/source/changelog.rst`, merging snippets in `docs/source/changelog/*/` as appropriate.
- [x] Update the JSON files in the `packaging/` folder with author and project information
- [x] Create a release candidate using `scripts/release`. See `scripts/release --help` for details.
- [x] Confirm that wheel and tar.gz are built for the release candidate on GitHub: https://github.com/Ptychography-4-0/ptychography/releases
- [x] Confirm that a new version with the most recent release candidate is created in the Zenodo.org sandbox TODO fix link https://example.com/fixme that is ready for submission.
- [x] Install release candidate packages in a clean environment (for example:
  `python -m pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple 'ptychography==0.1.0rc0'`
- [x] Make sure you have test files for all supported algorithms available
- [x] Run all examples and applications using the test files
    - [ ] Are parameters recognized correctly, as far as implemented?
    - [ ] Any bad default values?
    - [ ] Does the file open correctly?
    - [ ] Does the result change when the input parameters are changed?
    - [ ] All display channels present and looking reasonable?
    - [ ] Reasonable performance?
- [x] Run all examples and applications on Windows
- [x] Confirm that pull requests and issues are handled as intended, i.e. milestoned and merged in appropriate branch.

## After releasing on GitHub

- [x] Confirm that all release packages are built and release notes are up-to-date
- [x] Install release package
- [x] Confirm correct version info
- [x] confirm package upload to PyPI
- [x] Publish new version on zenodo.org
- [ ] Update documentation with new links, if necessary
    - [x] Add zenodo badge for the new release to Changelog page
- [x] Send announcement message on mailing list
- [x] Bump version in master branch to next .dev0

**Comment by uellue** [comment]
@sk1p now that CI is working, we can maybe set up the github.io page next? After that I can add all the links etc. :-)

**Comment by sk1p** [comment]
> now that CI is working, we can maybe set up the github.io page next? After that I can add all the links etc. :-)

https://ptychography-4-0.github.io/ptychography/

Done!

**Comment by uellue** [comment]
Maybe we can bake RC1 next to see how test.pypi.org and sandbox.zenodo.org work?

**Comment by sk1p** [comment]
> Maybe we can bake RC1 next to see how test.pypi.org and sandbox.zenodo.org work?

It's in the oven

**Comment by sk1p** [comment]
I'll continue with rc2 as the pypi upload etc. needs #40, see failure here:

https://dev.azure.com/ptycho40/ptycho40/_build/results?buildId=21&view=logs&j=38a51236-5fe5-5a53-0663-8be240de7f88&t=f0f1da31-f21c-5e95-1691-9d943bab5df0

**Comment by sk1p** [comment]
https://test.pypi.org/project/ptychography40/

**Comment by uellue** [comment]
https://sandbox.zenodo.org/record/748946

**Comment by sk1p** [comment]
> https://sandbox.zenodo.org/record/748946

Should we maybe clean up the `references*.bib` file? Right now, it's just a copy from the LiberTEM main repo, so we could remove most of the LiberTEM-specific entries here. That should make the "related identifiers" section of the zenodo deposition a bit more manageable.

**Comment by uellue** [comment]
> > https://sandbox.zenodo.org/record/748946
> 
> Should we maybe clean up the `references*.bib` file? Right now, it's just a copy from the LiberTEM main repo, so we could remove most of the LiberTEM-specific entries here. That should make the "related identifiers" section of the zenodo deposition a bit more manageable.

Yes, sounds good!

**Comment by uellue** [comment]
We could now start review by co-authors while we work on releasing LiberTEM 0.7 and LiberTEM-live 0.1, then merge #35, and then continue with this release?

**Comment by uellue** [comment]
Maybe we can bake RC3 after #41 and then ask the others for review of the homepage and Zenodo deposition?

**Comment by sk1p** [comment]
> We could now start review by co-authors while we work on releasing LiberTEM 0.7 and LiberTEM-live 0.1, then merge #35, and then continue with this release?

Sounds like a plan!

> Maybe we can bake RC3 after #41 and then ask the others for review of the homepage and Zenodo deposition?

In the oven.

**Comment by SimeonEhrig** [comment]
@uellue My ORCID is: https://orcid.org/0000-0002-8218-3116
