### ISSUE TITLE
Collect Numba coverage

### ISSUE THREAD

**Issue by uellue** [Ptychography-4-0/ptychography#48]
In #35 the coverage is poor because now most of the work is done within a Numba-compiled function, which only generates coverage if it is run with disabled Numba compilation.

For that reason we should run a separate CI pipeline with disabled Numba compilation on selected tests like in LiberTEM to get coverage.

**Comment by sk1p** [comment]
This is being worked on as part of #72 - when that is merged, we can easily make sure the coverage is counted properly by marking a few more tests as `with_numba`.

**Comment by sk1p** [comment]
Fixed in #73
