### ISSUE TITLE
Implement stitching procedure

### ISSUE THREAD

**Issue by heidemeissner** [Ptychography-4-0/ptychography#8]
Implement stitching procedure from Nashed et al. 2014. This is required at the end of a reconstruction performed individually for more than one subset of diffraction data  due to phase shifts being different for each subset and adjust the geometrical positions to one complete object.

**Comment by uellue** [comment]
The weighting of stitching parts is related to aggregating how much data/"strength" already contributed to the accumulated result vs the strength of the result that is being merged. Example: LiberTEM's StdDevUDF https://github.com/LiberTEM/LiberTEM/blob/master/src/libertem/udf/stddev.py based on "Numerically Stable Parallel Computation of (Co-) Variance" DOI : https://doi.org/10.1145/3221269.3223036

**Comment by heidemeissner** [comment]
Oleh (Munich) has a stitching routine available he wanted to send, any news from him?

**Comment by sk1p** [comment]
@Sniper2k ping - what is the status on your stitching routine?

/cc @bangunarya

**Comment by Sniper2k** [comment]
@sk1p 

Ready! Where should I upload it to?

**Comment by sk1p** [comment]
If you like you can add it to this repo

**Comment by uellue** [comment]
Closed with #29
